services:
  postgres:
    image: postgres:16-alpine
    container_name: supportdesk-lite-postgres
    environment:
      POSTGRES_DB: supportdesk_lite
      POSTGRES_USER: supportdesk
      POSTGRES_PASSWORD: supportdesk
    ports:
      - "5432:5432"
    volumes:
      - supportdesk_postgres_data:/var/lib/postgresql/data

volumes:
  supportdesk_postgres_data:
