spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/supportdesk_lite}
    username: ${DB_USERNAME:supportdesk}
    password: ${DB_PASSWORD:supportdesk}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
